# Database properties
spring:
  datasource:
    url: jdbc:sqlserver://LAPTOP-LJRLVS6G:1433;databaseName=pennyguard
    username: sa
    password: 123
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        ddl-auto: update
        format_sql: true

# JWT (JSON Web Token) expiration time
app:
  jwtExpirationMs: 60000

