# Database properties
spring:
  datasource:
    url: jdbc:sqlserver://LAPTOP-LJRLVS6G:1433;databaseName=pennyguard
    username: sa
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  flyway:
    repair: true
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true
    connectRetries: 3
    connectRetriesInterval: 600000
  # JPA (Java Persistence API) configuration
  jpa:
    hibernate:
      # Automatic DDL (Data Definition Language) generation strategy:
      # - create: creates database schema on startup (note: this may drop existing schema)
      ddl-auto: update
      # Enable SQL logging for better debugging
      show-sql: true
    properties:
      # Hibernate dialect for SQL Server 2012
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        # Format SQL queries for better readability
        format_sql: true

# Application-specific configurations
app:
  # JWT (JSON Web Token) expiration time in milliseconds
  jwtExpirationMs: 900000000
